### ISSUE TITLE
JOSS Paper title to broad

### ISSUE THREAD

**Issue by junghans** [antoinediez/Sisyphe#3]
Related to https://github.com/openjournals/joss-reviews/issues/3653.

Coming from the molecular dynamics (MD) background the title of the JOSS Paper _A Python package for the Simulation of Systems of Particles with High Efficiency_ seems a bit too broad as MD is even mentioned at all, maybe a more toned-down title like _A Python package for the Simulation of Systems of interacting mean-field Particles with High Efficiency_ would be better.

**Comment by pdebuyl** [comment]
@antoinediez keep in mind that the title of the paper and of the zenodo archive of the repository must be identical.

**Comment by antoinediez** [comment]
Thank you for your feedback! 
I do agree, the title that you propose is more precise. 
@pdebuyl  I changed the title of the paper and I will make sure that the title of the Zenodo archive will be the same. However I don't think that I can change the title of the JOSS issue, but I don't know if it is necessary?

**Comment by junghans** [comment]
Updated the issue!

Where is Zenodo pulling the title from? Is it from the repository description? (Which is still "Simulation of Systems of Particles with High Efficiency")

**Comment by antoinediez** [comment]
I updated the repository description. 

Once the paper will (hopefully) be accepted, I will make a new release and the title of the Zenodo archive will be the title of this release. So it shouldn't be a problem.
